### PR TITLE
Add profile and update code/catalogs

### PR DESCRIPTION
**Pull request by tresoldi**
As discussed at https://github.com/lexibank/polyglottaafricana/issues/3

This PR adds the orthographic profile that I could do in some hours. It is not perfect and some phoneme distributions seem strange, such as for rhotic vowels, but the profile itself was not too difficult as it was mostly following Africanist practices. Getting 100% coverage helped, as usual, in fixing some misformed values, cleaning code, etc.

My estimate is that, for at least 90-95% of the entries, the segmentation and the SCA sound class is right. As usual, no issue in keeping this in a separate branch to bootstrap individual profiles or have experts review.

The PR also updates the code to newer standards, such as proper identifiers, tests, etc.

### CODE REVIEW

**Review by LinguList — APPROVED** [review]
I think it is fine. Can you also look into adding the source, making the bibtex there, etc.? A notesfield, mentioning this comes from reflex would also be useful. There is a list in reflex with all languages and ISO code, or do we have the language codes already?

**Comment by tresoldi** [comment]
I'll do the bibtex now.

As for the languages, I don't know, the language mapping was first pushed by @xrotwang . If nobody has it, I can look it later (pulling codes from Glottolog if necessary, they should match, right?).

**Comment by tresoldi** [comment]
@LinguList I've updated it; please note that in `CONTRIBUTORS.md` I've listed Segerer as an author (he was listed as maintainer along with @xrotwang ). Let me know if it should be changed.

**Comment by LinguList** [comment]
This is excellent, @tresoldi, we should give them curators more space,
for ourselves, it is not about being quoted for a dataset, but to be
able to use the data, and to push open lexical data. I also added many
people as authors, whenever I know them and know they consent.

**Comment by LinguList** [comment]
MISUNDERSTANDING from my side! Glottocodes are there, all super. Only concepticon mapping is missing, and we have the list on google drive, just need to finalize it.

**Comment by LinguList** [comment]
well done, @tresoldi !

**Pull request merged**
