### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by chrzyki**

### CODE REVIEW

**Comment by FredericBlum** [comment]
Does this address the duplicated rows from https://github.com/lexibank/lexibank-analysed/issues/49#issuecomment-2067757206 ?

**Comment by chrzyki** [comment]
No, likewise, will be a separate PR. 'Release prep' wasn't the best name for this branch. :)

**Comment by FredericBlum** [comment]
Sorry didnt want to merge, but approve. But I guess not having to revert is ok?

**Comment by chrzyki** [comment]
All good, no worries, I'll just take note of the TODO for this PR in the data set sheet.

**Comment by chrzyki** [comment]
The number of repeated forms was considerably reduced due to changing the parsing of the source data: from 2409 occurrences in the old release two 21 occurrences in the new release (which indeed look like repeated forms and not a systematic error in handing the source data).

**Pull request merged**
